### ISSUE TITLE
cannot enter the eval stage

### ISSUE THREAD

**Issue by ETHRuiGong** [Spandan-Madan/Pytorch_fine_tuning_Tutorial#6]
Hello, I am now using the programme for the finetune of "Resnet50". And I just change the "Resnet 18" in the original programme to the "Resnet 50". But the problem is that after the first training stage, it will break automatically and does not give any error information. Anyone can give some help? Thanks a lot!

**Comment by ETHRuiGong** [comment]
And sometimes, it can finish the first training and evaluation stage, but then break automatically and cannot enter the epoch2.

**Comment by Spandan-Madan** [comment]
What's the error stack? 

I just updated the code to PyTorch 0.4 and re-ran the code, it works fine

It is possible that the program terminates if you run out of RAM, try reducing the Batch size in the config file, if it was a RAM issue, it will sort out.

**Comment by Spandan-Madan** [comment]
Closing this issue for now as it seems to work on a fresh new system with the updated code, in case you or someone else still runs into it, please reopen the issue!
